# Generated by Django 5.1.2 on 2024-10-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('corrente', 'Corrente'), ('dinheiro', 'Dinheiro'), ('poupanca', 'Poupança'), ('investimentos', 'Investimentos'), ('outros', 'Outros')], max_length=50)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FF00FF', 'Magenta'), ('#00FFFF', 'Cyan')], max_length=7)),
                ('include_calc', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
