# Generated by Django 5.1.11 on 2026-03-13 00:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('social_name', models.CharField(max_length=150, verbose_name='Nome Social')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_user_custom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('corrente', 'Corrente'), ('dinheiro', 'Dinheiro'), ('poupanca', 'Poupança'), ('investimentos', 'Investimentos'), ('outros', 'Outros')], max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('include_calc', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('icon', models.CharField(max_length=20)),
                ('type_category', models.CharField(choices=[('despesas', 'Despesas'), ('receitas', 'Receitas')], max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('color', models.CharField(max_length=7, verbose_name='Cor')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limite')),
                ('closing_day', models.PositiveIntegerField(verbose_name='Dia de fechamento')),
                ('due_day', models.PositiveIntegerField(verbose_name='Dia de vencimento')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'db_table': 'credit_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_month', models.PositiveIntegerField(verbose_name='Mês de referência')),
                ('reference_year', models.PositiveIntegerField(verbose_name='Ano de referência')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('paga', 'Paga')], default='aberta', max_length=10, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor total')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.creditcard', verbose_name='Cartão de Crédito')),
                ('paid_via_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to='api.account', verbose_name='Conta de pagamento')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'invoice',
                'ordering': ['-reference_year', '-reference_month'],
                'unique_together': {('credit_card', 'reference_month', 'reference_year')},
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('image_num', models.IntegerField(blank=True, null=True, verbose_name='Imagem')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Parente',
                'verbose_name_plural': 'Parentes',
                'db_table': 'relative',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=10, verbose_name='Frequência')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Intervalo')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('occurrences_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de ocorrências')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='api.account', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='api.category', verbose_name='Categoria')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='api.creditcard', verbose_name='Cartão de Crédito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='api.relative', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Regra de Recorrência',
                'verbose_name_plural': 'Regras de Recorrência',
                'db_table': 'recurring_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditcard',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='api.relative', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='category',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.relative', verbose_name='Parente'),
        ),
        migrations.AddField(
            model_name='account',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.relative', verbose_name='Parente'),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('user', 'relative', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'relative', 'name', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'relative', 'name')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_pair_id', models.UUIDField(blank=True, null=True, verbose_name='ID do Par de Transferência')),
                ('transfer_direction', models.CharField(blank=True, choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=6, null=True, verbose_name='Direção da Transferência')),
                ('installment_group_id', models.UUIDField(blank=True, null=True, verbose_name='ID do Grupo de Parcelas')),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da Parcela')),
                ('installment_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Parcelas')),
                ('type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferência')], max_length=15, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('date', models.DateField(verbose_name='Data')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.account', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.category', verbose_name='Categoria')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.invoice', verbose_name='Fatura')),
                ('recurring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.recurringrule', verbose_name='Regra de Recorrência')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.relative', verbose_name='Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'relative', 'date'], name='idx_transaction_period'), models.Index(fields=['account', 'date'], name='idx_transaction_account'), models.Index(fields=['category', 'date'], name='idx_transaction_category'), models.Index(fields=['recurring_rule', 'date'], name='idx_transaction_recurring'), models.Index(fields=['installment_group_id'], name='idx_transaction_installment'), models.Index(fields=['invoice'], name='idx_transaction_invoice')],
            },
        ),
    ]
