# Generated by Django 5.1.11 on 2026-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_direction',
            field=models.CharField(blank=True, choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=6, null=True, verbose_name='Direção da Transferência'),
        ),
    ]
